feat: update stacks-core bindings to the 3.2 release (#1782)
## Description

This PR updates the Stacks bindings in preparation for Epoch 3.2. This
is needed primarily due to our use of the stacks-core API response types
which use enums (e.g. ´StacksBlockId::Epoch32` does not exist and
results in a deserialization error).

⚠️ This PR targets `release/1.0.3`, which is a copy of the `v1.0.2` tag.

## Changes

- Updates the stacks-core bindings (`clarity`, `stackslib`,
`stacks-common`) to the 3.2 release
(`6c769636d5d598d1872960ca2744ad1b64fa6385`).
- Updates our stacks-node image tags to the 3.2 release.
- Addresses breaking changes with the 3.2 version of the stacks-core
libs.
- Pulled in `.github/`, `Makefile` and a number of files from `docker/`
from `main`.
- Needed to add `chrono` explicitly with a compatible version, otherwise
we get:
  ```
  error: failed to select a version for `chrono`.
... required by package `stacks-common v0.0.1
(https://github.com/stacks-network/stacks-core?rev=6c769636d5d598d1872960ca2744ad1b64fa6385#6c769636)`
... which satisfies git dependency `stacks-common` of package
`emily-handler v0.1.0
(/Users/cylwit/Code/github.com/stacks-network/sbtc/emily/handler)`
... which satisfies path dependency `emily-handler` (locked to 0.1.0) of
package `emily-openapi-spec v0.1.0
(/Users/cylwit/Code/github.com/stacks-network/sbtc/emily/openapi-gen)`
  versions that meet the requirements `^0.4.41` are: 0.4.41
  
  all possible versions conflict with previously selected packages.
  
    previously selected package `chrono v0.4.38`
... which satisfies dependency `chrono_0_4 = "^0.4.20"` (locked to
0.4.38) of package `serde_with v3.8.1`
... which satisfies dependency `serde_with = "^3.8"` (locked to 3.8.1)
of package `private-emily-client v0.1.0
(/Users/cylwit/Code/github.com/stacks-network/sbtc/.generated-sources/emily/client/rust/private)`
  
failed to select a version for `chrono` which could resolve this
conflict
  make: *** [emily-client-build] Error 101
  ```

## Testing Information

All tests pass, and @matteojug and I have tested on devenv.

## Checklist

- [x] I have performed a self-review of my code
- [x] My changes generate no new warnings
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream
modules